Modify params
Periondao/perion-liquidity-mining pull request #3
Opened 2022-11-23 06:58 UTC by perionjames

2022-11-23 06:59 UTC, perionjames commented on tasks/deploy/full.ts
>  const LP = "0xcCb63225a7B19dcF66717e4d40C9A72B39331d61";
@amosperion any idea what these should be?

2022-11-23 06:59 UTC, perionjames commented on tasks/deploy/full.ts
>  const multisig = "0x7e9e4c0876b2102f33a1d82117cc73b7fddd0032";
@amosperion as above

2022-11-29 04:43 UTC, perionjames commented
@amosperion @geoshak up for review, would like a few eyes on the formula...

2022-11-30 02:34 UTC, amosperion requested changes

2022-11-30 02:34 UTC, amosperion commented on tasks/deploy/full.ts
>  const multisig = "0x7e9e4c0876b2102f33a1d82117cc73b7fddd0032";
0x12D73beE50F0b9E06B35Fdef93E563C965796482

2022-11-30 02:34 UTC, amosperion commented on tasks/deploy/full.ts
>  const multisig = "0x7e9e4c0876b2102f33a1d82117cc73b7fddd0032";
That's the Perion Multisig safe

2022-11-30 02:34 UTC, amosperion commented on tasks/deploy/full.ts
>  const LP = "0xcCb63225a7B19dcF66717e4d40C9A72B39331d61";
Is LP where the current pool is?

2022-11-30 02:34 UTC, amosperion commented on tasks/deploy/full.ts
>  const LP = "0xcCb63225a7B19dcF66717e4d40C9A72B39331d61";
0x45b6ffb13e5206dafe2cc8780e4ddc0e32496265

2022-11-30 02:38 UTC, merged

2022-11-30 13:43 UTC, geoshak commented
I'll run the test locally in the future and share comments, if any.